title: Hung Duy Nguyen # your name (or website title) here
logo: "/images/Hung_Nguyen_Duy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years of Control and Automation of Mechanical Engineering.
  <br><br>
  Currently, I am working and pursuing my M.S. degree in the Vehicle Optimization Intelligent Control Energy Laboratory (V.O.I.C.E)
  under the supervision of Prof. Kyoungseok Han at the School of Mechanical Engineering, Kyungpook National University, Daegu, South Korea.
  <br><br>
  <a href="https://www.linkedin.com/in/nguyen-hung-2a1b82223/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
