title: Hung Duy Nguyen # your name (or website title) here
logo: "/images/Hung_Nguyen_Duy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years of Control and Automation of Mechanical Engineering with the Suspension System (Quarter Car, Half Car, and Full Car modelings). In 2020, I received a B.S. degree in mechanical engineering from the University of Transport and Communications, Department of Mechanical Engineering, Vietnam.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/nguyen-hung-2a1b82223/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
